owner: buildwithmanag
repo: retire-wise-status

sites:
  - name: RetireWise Server (mana)
    url: https://sgnzli35s4.execute-api.us-east-1.amazonaws.com/mana/health

status-website:
  baseUrl: /retire-wise-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RetireWise Status
  introTitle: "RetireWise Operational Monitoring"
  introMessage: Real-time uptime monitoring for RetireWise environments.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
